"""Pharmacy: prescriptions, fills, refills, adherence, pharmacy choice, drug information.

Drug information and interaction warnings come ONLY from the curated demo tables
(`drug_monographs`, `drug_interactions`). Nothing here is generated by a language model, and the
interaction list is not exhaustive: the UI tells patients to confirm with a pharmacist.

Access: patients reach their own medications. Clinicians reach patients in their organization;
only the prescriber decides a refill request. Administrators have no access to medication data.
"""

from __future__ import annotations

from datetime import date, timedelta
from typing import Literal
from uuid import UUID

from fastapi import APIRouter, HTTPException, status
from psycopg import Connection
from pydantic import BaseModel, ConfigDict, Field, StrictInt

from bioverse import audit
from bioverse.auth import Clinician, CurrentUser, Patient, User, assert_patient_access
from bioverse.db import DbConn
from bioverse.db.seeds.context import SeedContext

router = APIRouter(prefix="/api/pharmacy", tags=["pharmacy"])

Conn = DbConn

DRUG_INFO_NOTICE = (
    "Demo drug information, curated for this demo. It is not complete and is not medical advice. "
    "Ask your pharmacist or prescriber about your medicines."
)
INTERACTION_NOTICE = (
    "This checks a short curated list of known interactions only. It is not exhaustive: always confirm "
    "with your pharmacist before starting or combining medicines."
)
DEMO_PHARMACY_NOTICE = "Demo pharmacies. Fill updates are simulated; no real pharmacy receives these requests."
ADHERENCE_TARGET = 80


def clinic_today() -> date:
    return SeedContext().today


def _patient_scope(conn: Connection, user: User, patient_id: str | None) -> str:
    """Patients: themselves. Clinicians: patients in their organization (patient_id required)."""
    if patient_id:
        try:
            patient_id = str(UUID(patient_id))
        except ValueError:
            raise HTTPException(status.HTTP_404_NOT_FOUND, "Patient not found") from None
    if user.role == "patient" and user.patient_id:
        if patient_id and patient_id != user.patient_id:
            raise HTTPException(status.HTTP_403_FORBIDDEN, "Not your record")
        return user.patient_id
    if user.role == "clinician" and user.practitioner_id:
        if not patient_id:
            raise HTTPException(status.HTTP_400_BAD_REQUEST, "patient_id is required")
        assert_patient_access(conn, user, patient_id)
        return patient_id
    raise HTTPException(status.HTTP_403_FORBIDDEN, "Medication records are available to the patient and their clinicians")


# --- Pharmacy directory ----------------------------------------------------------------------


PHARMACY_COLS = "id::text, name, address, phone, hours, distance_km, open_24_hours"


@router.get("/pharmacies")
def list_pharmacies(conn: Conn, user: CurrentUser, open_24_hours: bool = False, q: str | None = None) -> dict:
    rows = conn.execute(
        f"""
        SELECT {PHARMACY_COLS} FROM pharmacies
        WHERE (NOT %(h)s OR open_24_hours) AND (%(q)s::text IS NULL OR name ILIKE '%%' || %(q)s || '%%'
                                                  OR address ILIKE '%%' || %(q)s || '%%')
        ORDER BY distance_km, name
        """,
        {"h": open_24_hours, "q": (q or "").strip() or None},
    ).fetchall()
    return {"pharmacies": rows, "notice": DEMO_PHARMACY_NOTICE}


def _preferred(conn: Connection, patient_id: str) -> dict | None:
    return conn.execute(
        f"""
        SELECT {', '.join('ph.' + c.strip() for c in PHARMACY_COLS.split(','))}
        FROM patient_pharmacy_preferences pp JOIN pharmacies ph ON ph.id = pp.pharmacy_id
        WHERE pp.patient_id = %s
        """,
        (patient_id,),
    ).fetchone()


@router.get("/preferred-pharmacy")
def get_preferred(conn: Conn, user: CurrentUser, patient_id: str | None = None) -> dict:
    pid = _patient_scope(conn, user, patient_id)
    return {"pharmacy": _preferred(conn, pid)}


class PreferredIn(BaseModel):
    model_config = ConfigDict(extra="forbid")
    pharmacy_id: str


@router.put("/preferred-pharmacy")
def set_preferred(body: PreferredIn, conn: Conn, user: Patient) -> dict:
    exists = conn.execute("SELECT 1 FROM pharmacies WHERE id::text = %s", (body.pharmacy_id,)).fetchone()
    if exists is None:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Pharmacy not found")
    conn.execute(
        """
        INSERT INTO patient_pharmacy_preferences (patient_id, pharmacy_id) VALUES (%s, %s)
        ON CONFLICT (patient_id) DO UPDATE SET pharmacy_id = EXCLUDED.pharmacy_id, updated_at = now()
        """,
        (user.patient_id, body.pharmacy_id),
    )
    audit.record(conn, action="preferred_pharmacy_set", entity_type="pharmacy", entity_id=body.pharmacy_id,
                 actor=user, patient_id=user.patient_id)
    return {"pharmacy": _preferred(conn, user.patient_id)}


# --- Adherence -------------------------------------------------------------------------------


def adherence_stats(taken: set[date], start: date | None, today: date) -> dict:
    """Patient-logged adherence. Today counts only once it's logged, so an unfinished day isn't a miss.

    Days before tracking started (first pickup) are excluded from every window.
    """
    if start is None:
        return {"tracking": False, "pct_7": None, "pct_30": None, "taken_7": 0, "days_7": 0, "taken_30": 0,
                "days_30": 0, "streak": 0, "taken_today": False}
    taken_today = today in taken

    def window(n: int) -> tuple[int, int]:
        # The last n days, ending today once today's dose is logged, otherwise ending yesterday.
        last = today if taken_today else today - timedelta(days=1)
        first = max(start, last - timedelta(days=n - 1))
        if last < first:
            return 0, 0
        days = (last - first).days + 1
        hits = sum(1 for d in taken if first <= d <= last)
        return hits, days

    def pct(hits: int, days: int) -> int | None:
        return None if days == 0 else (200 * hits + days) // (2 * days)

    t7, d7 = window(7)
    t30, d30 = window(30)
    streak = 0
    d = today if taken_today else today - timedelta(days=1)
    while d in taken and d >= start:
        streak += 1
        d -= timedelta(days=1)
    return {"tracking": True, "pct_7": pct(t7, d7), "pct_30": pct(t30, d30), "taken_7": t7, "days_7": d7,
            "taken_30": t30, "days_30": d30, "streak": streak, "taken_today": taken_today}


def _tracking_start(conn: Connection, rx_id: str, tz) -> date | None:
    row = conn.execute(
        "SELECT min(picked_up_at) AS at FROM medication_dispenses WHERE medication_request_id = %s AND picked_up_at IS NOT NULL",
        (rx_id,),
    ).fetchone()
    return row["at"].astimezone(tz).date() if row and row["at"] else None


def adherence_for(conn: Connection, rx_id: str) -> dict:
    ctx = SeedContext()
    today = ctx.today
    start = _tracking_start(conn, rx_id, ctx.tz)
    logs = conn.execute(
        "SELECT taken_on FROM medication_adherence_logs WHERE medication_request_id = %s AND taken_on > %s",
        (rx_id, today - timedelta(days=60)),
    ).fetchall()
    taken = {r["taken_on"] for r in logs}
    stats = adherence_stats(taken, start, today)
    stats["started_on"] = start
    stats["days"] = [
        {"date": today - timedelta(days=i), "taken": (today - timedelta(days=i)) in taken,
         "tracked": start is not None and today - timedelta(days=i) >= start}
        for i in range(13, -1, -1)
    ]
    stats["target_pct"] = ADHERENCE_TARGET
    return stats


# --- Prescriptions ---------------------------------------------------------------------------


RX_SELECT = """
    SELECT m.id::text, m.patient_id::text, m.drug_code, m.drug_name, m.strength, m.sig, m.quantity,
           m.refills_authorized, m.refills_remaining, m.status, m.authored_at,
           pr.id::text AS prescriber_id, pr.name AS prescriber_name,
           ph.id::text AS pharmacy_id, ph.name AS pharmacy_name,
           d.id::text AS dispense_id, d.status AS dispense_status, d.fill_number, d.sent_at, d.ready_at,
           d.picked_up_at, dph.name AS dispense_pharmacy_name, dph.phone AS dispense_pharmacy_phone,
           (SELECT r.id::text FROM refill_requests r WHERE r.medication_request_id = m.id AND r.status = 'pending_approval')
               AS pending_refill_id
    FROM medication_requests m
    JOIN practitioners pr ON pr.id = m.prescriber_id
    LEFT JOIN pharmacies ph ON ph.id = m.pharmacy_id
    LEFT JOIN LATERAL (
        SELECT * FROM medication_dispenses x WHERE x.medication_request_id = m.id ORDER BY x.fill_number DESC LIMIT 1
    ) d ON true
    LEFT JOIN pharmacies dph ON dph.id = d.pharmacy_id
"""


def _rx_out(conn: Connection, row: dict) -> dict:
    row["latest_fill"] = None
    if row["dispense_id"]:
        row["latest_fill"] = {
            "id": row["dispense_id"], "status": row["dispense_status"], "fill_number": row["fill_number"],
            "sent_at": row["sent_at"], "ready_at": row["ready_at"], "picked_up_at": row["picked_up_at"],
            "pharmacy_name": row["dispense_pharmacy_name"], "pharmacy_phone": row["dispense_pharmacy_phone"],
        }
    for k in ("dispense_id", "fill_number", "sent_at", "ready_at", "picked_up_at", "dispense_pharmacy_name",
              "dispense_pharmacy_phone"):
        row.pop(k)
    row["adherence"] = adherence_for(conn, row["id"]) if row["status"] == "active" else None
    row["last_refill_request"] = conn.execute(
        """
        SELECT id::text, status, decision_note, decided_at, created_at FROM refill_requests
        WHERE medication_request_id = %s ORDER BY created_at DESC LIMIT 1
        """,
        (row["id"],),
    ).fetchone()
    return row


@router.get("/prescriptions")
def list_prescriptions(conn: Conn, user: CurrentUser, patient_id: str | None = None) -> dict:
    pid = _patient_scope(conn, user, patient_id)
    rows = conn.execute(
        RX_SELECT + """
        WHERE m.patient_id = %s
        ORDER BY (m.status IN ('active', 'on_hold')) DESC, m.authored_at DESC
        """,
        (pid,),
    ).fetchall()
    audit.record(conn, action="prescriptions_viewed", entity_type="medication_request", actor=user, patient_id=pid)
    return {"prescriptions": [_rx_out(conn, r) for r in rows], "notice": DEMO_PHARMACY_NOTICE}


def _load_rx(conn: Connection, user: User, rx_id: str, lock: bool = False) -> dict:
    if lock:
        conn.execute("SELECT 1 FROM medication_requests WHERE id::text = %s FOR UPDATE", (rx_id,))
    row = conn.execute(RX_SELECT + " WHERE m.id::text = %s", (rx_id,)).fetchone()
    if row is None:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Prescription not found")
    _patient_scope(conn, user, row["patient_id"])
    return row


@router.get("/prescriptions/{rx_id}")
def get_prescription(rx_id: str, conn: Conn, user: CurrentUser) -> dict:
    row = _rx_out(conn, _load_rx(conn, user, rx_id))
    row["fills"] = conn.execute(
        """
        SELECT d.id::text, d.fill_number, d.status, d.sent_at, d.ready_at, d.picked_up_at, ph.name AS pharmacy_name
        FROM medication_dispenses d JOIN pharmacies ph ON ph.id = d.pharmacy_id
        WHERE d.medication_request_id = %s ORDER BY d.fill_number DESC
        """,
        (rx_id,),
    ).fetchall()
    row["refill_requests"] = conn.execute(
        """
        SELECT id::text, status, patient_note, decision_note, decided_at, created_at
        FROM refill_requests WHERE medication_request_id = %s ORDER BY created_at DESC
        """,
        (rx_id,),
    ).fetchall()
    row["drug_info"] = _monograph(conn, row["drug_code"])
    audit.record(conn, action="prescription_viewed", entity_type="medication_request", entity_id=rx_id, actor=user,
                 patient_id=row["patient_id"])
    return row


# --- Fills (demo pharmacy) -------------------------------------------------------------------


def _load_fill(conn: Connection, user: User, dispense_id: str) -> dict:
    row = conn.execute(
        """
        SELECT d.id::text, d.status, d.patient_id::text, d.medication_request_id::text, m.drug_name, m.strength
        FROM medication_dispenses d JOIN medication_requests m ON m.id = d.medication_request_id
        WHERE d.id::text = %s FOR UPDATE OF d
        """,
        (dispense_id,),
    ).fetchone()
    if row is None or row["patient_id"] != user.patient_id:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Fill not found")
    return row


NEXT_FILL_STATUS = {"sent": "received", "received": "ready"}


@router.post("/fills/{dispense_id}/simulate-update")
def simulate_pharmacy_update(dispense_id: str, conn: Conn, user: Patient) -> dict:
    """Demo only: stands in for the pharmacy's status message (sent -> received -> ready)."""
    fill = _load_fill(conn, user, dispense_id)
    nxt = NEXT_FILL_STATUS.get(fill["status"])
    if nxt is None:
        raise HTTPException(status.HTTP_409_CONFLICT, "The pharmacy has nothing more to update on this fill")
    conn.execute(
        "UPDATE medication_dispenses SET status = %s, ready_at = CASE WHEN %s = 'ready' THEN now() ELSE ready_at END WHERE id::text = %s",
        (nxt, nxt, dispense_id),
    )
    audit.record(conn, action=f"fill_{nxt}", entity_type="medication_dispense", entity_id=dispense_id, actor=user,
                 agent="demo-pharmacy", patient_id=user.patient_id)
    return {"id": dispense_id, "status": nxt}


@router.post("/fills/{dispense_id}/pickup")
def confirm_pickup(dispense_id: str, conn: Conn, user: Patient) -> dict:
    fill = _load_fill(conn, user, dispense_id)
    if fill["status"] != "ready":
        raise HTTPException(status.HTTP_409_CONFLICT, "This fill isn't ready for pickup yet")
    conn.execute(
        "UPDATE medication_dispenses SET status = 'picked_up', picked_up_at = now() WHERE id::text = %s", (dispense_id,)
    )
    audit.record(conn, action="fill_picked_up", entity_type="medication_dispense", entity_id=dispense_id, actor=user,
                 patient_id=user.patient_id)
    return {"id": dispense_id, "status": "picked_up"}


# --- Refill requests -------------------------------------------------------------------------


class RefillIn(BaseModel):
    model_config = ConfigDict(extra="forbid")
    note: str | None = Field(default=None, max_length=500)


def _new_fill(conn: Connection, rx: dict, pharmacy_id: str) -> str:
    n = conn.execute(
        "SELECT coalesce(max(fill_number), 0) + 1 AS n FROM medication_dispenses WHERE medication_request_id = %s",
        (rx["id"],),
    ).fetchone()["n"]
    return conn.execute(
        """
        INSERT INTO medication_dispenses (medication_request_id, patient_id, pharmacy_id, fill_number, status)
        VALUES (%s, %s, %s, %s, 'sent') RETURNING id::text
        """,
        (rx["id"], rx["patient_id"], pharmacy_id, n),
    ).fetchone()["id"]


@router.post("/prescriptions/{rx_id}/refill-requests", status_code=status.HTTP_201_CREATED)
def request_refill(rx_id: str, body: RefillIn, conn: Conn, user: Patient) -> dict:
    rx = _load_rx(conn, user, rx_id, lock=True)
    if rx["status"] != "active":
        raise HTTPException(
            status.HTTP_409_CONFLICT,
            {"code": "not_active", "message": "This prescription isn't active. Message your care team if you still need it."},
        )
    if rx["pending_refill_id"]:
        raise HTTPException(status.HTTP_409_CONFLICT,
                            {"code": "pending", "message": "A refill request is already waiting for your prescriber."})
    if rx["dispense_status"] in ("sent", "received", "ready"):
        raise HTTPException(
            status.HTTP_409_CONFLICT,
            {"code": "fill_in_progress",
             "message": "Your last fill is still in progress or waiting for pickup at the pharmacy."},
        )
    preferred = _preferred(conn, rx["patient_id"])
    pharmacy_id = preferred["id"] if preferred else rx["pharmacy_id"]
    if not pharmacy_id:
        raise HTTPException(status.HTTP_409_CONFLICT,
                            {"code": "no_pharmacy", "message": "Choose a pharmacy first."})
    note = (body.note or "").strip() or None
    label = f"{rx['drug_name']} {rx['strength']}"

    if rx["refills_remaining"] > 0:
        dispense_id = _new_fill(conn, rx, pharmacy_id)
        conn.execute("UPDATE medication_requests SET refills_remaining = refills_remaining - 1 WHERE id::text = %s", (rx_id,))
        req = conn.execute(
            """
            INSERT INTO refill_requests (medication_request_id, patient_id, prescriber_id, pharmacy_id, status,
                                         patient_note, dispense_id)
            VALUES (%s, %s, %s, %s, 'sent_to_pharmacy', %s, %s) RETURNING id::text, status, created_at
            """,
            (rx_id, rx["patient_id"], rx["prescriber_id"], pharmacy_id, note, dispense_id),
        ).fetchone()
        audit.record(conn, action="refill_sent_to_pharmacy", entity_type="refill_request", entity_id=req["id"],
                     actor=user, patient_id=rx["patient_id"],
                     detail={"medication_request_id": rx_id, "dispense_id": dispense_id,
                             "refills_remaining": rx["refills_remaining"] - 1})
        return {**req, "requires_approval": False, "dispense_id": dispense_id,
                "message": f"Sent to the pharmacy. {rx['refills_remaining'] - 1} refills left after this one."}

    req = conn.execute(
        """
        INSERT INTO refill_requests (medication_request_id, patient_id, prescriber_id, pharmacy_id, status, patient_note)
        VALUES (%s, %s, %s, %s, 'pending_approval', %s) RETURNING id::text, status, created_at
        """,
        (rx_id, rx["patient_id"], rx["prescriber_id"], pharmacy_id, note),
    ).fetchone()
    body_text = f"No refills remaining on {label} ({rx['sig']})."
    if note:
        body_text += f" Patient note: \"{note}\""
    item = conn.execute(
        """
        INSERT INTO review_items (kind, patient_id, practitioner_id, ref_id, title, body, priority, link)
        VALUES ('refill_request', %s, %s, %s, %s, %s, 'routine', '/clinician/refills') RETURNING id::text
        """,
        (rx["patient_id"], rx["prescriber_id"], req["id"], f"Refill request · {label}", body_text),
    ).fetchone()
    conn.execute("UPDATE refill_requests SET review_item_id = %s WHERE id = %s", (item["id"], req["id"]))
    audit.record(conn, action="refill_requested", entity_type="refill_request", entity_id=req["id"], actor=user,
                 patient_id=rx["patient_id"], detail={"medication_request_id": rx_id, "review_item_id": item["id"]})
    return {**req, "requires_approval": True, "dispense_id": None,
            "message": f"No refills are left, so we've asked {rx['prescriber_name']} to approve it. "
                       "You'll see the answer here."}


REFILL_QUEUE_SELECT = """
    SELECT r.id::text, r.status, r.patient_note, r.decision_note, r.decided_at, r.created_at,
           r.review_item_id::text, p.id::text AS patient_id, p.name AS patient_name, p.birth_date,
           m.id::text AS medication_request_id, m.drug_code, m.drug_name, m.strength, m.sig, m.quantity,
           m.refills_authorized, m.refills_remaining, m.authored_at, ph.name AS pharmacy_name
    FROM refill_requests r
    JOIN patients p ON p.id = r.patient_id
    JOIN medication_requests m ON m.id = r.medication_request_id
    JOIN pharmacies ph ON ph.id = r.pharmacy_id
"""


@router.get("/clinician/refill-requests")
def refill_queue(conn: Conn, user: Clinician,
                 status_filter: Literal["pending_approval", "decided", "all"] = "pending_approval") -> list[dict]:
    rows = conn.execute(
        REFILL_QUEUE_SELECT + """
        WHERE r.prescriber_id = %(pr)s AND p.organization_id = %(org)s
          AND r.status IN ('pending_approval', 'approved', 'denied')
          AND (%(f)s = 'all' OR (%(f)s = 'pending_approval' AND r.status = 'pending_approval')
               OR (%(f)s = 'decided' AND r.status IN ('approved', 'denied')))
        ORDER BY (r.status = 'pending_approval') DESC, r.created_at DESC
        LIMIT 100
        """,
        {"pr": user.practitioner_id, "org": user.organization_id, "f": status_filter},
    ).fetchall()
    for r in rows:
        r["adherence"] = adherence_for(conn, r["medication_request_id"])
        r["interactions"] = interactions_for(conn, r["patient_id"])["warnings"]
    return rows


class RefillDecisionIn(BaseModel):
    model_config = ConfigDict(extra="forbid")
    decision: Literal["approve", "deny"]
    note: str | None = Field(default=None, max_length=1000)
    additional_refills: StrictInt = Field(default=0, ge=0, le=11)


@router.post("/clinician/refill-requests/{request_id}/decision")
def decide_refill(request_id: str, body: RefillDecisionIn, conn: Conn, user: Clinician) -> dict:
    req = conn.execute(
        """
        SELECT r.id::text, r.status, r.patient_id::text, r.prescriber_id::text, r.pharmacy_id::text,
               r.review_item_id::text, r.medication_request_id::text
        FROM refill_requests r WHERE r.id::text = %s FOR UPDATE
        """,
        (request_id,),
    ).fetchone()
    if req is None:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Refill request not found")
    assert_patient_access(conn, user, req["patient_id"])
    if req["prescriber_id"] != user.practitioner_id:
        raise HTTPException(status.HTTP_403_FORBIDDEN, "Only the prescriber can decide this refill")
    if req["status"] != "pending_approval":
        raise HTTPException(status.HTTP_409_CONFLICT, "This refill request has already been decided")
    note = (body.note or "").strip() or None
    if body.decision == "deny" and not note:
        raise HTTPException(status.HTTP_422_UNPROCESSABLE_CONTENT, "Add a note for the patient explaining the denial")
    if body.decision == "deny" and body.additional_refills:
        raise HTTPException(status.HTTP_422_UNPROCESSABLE_CONTENT, "Refills can only be added when approving")

    rx = conn.execute(
        "SELECT id::text, patient_id::text, status, drug_name, strength FROM medication_requests WHERE id = %s FOR UPDATE",
        (req["medication_request_id"],),
    ).fetchone()
    dispense_id = None
    if body.decision == "approve":
        if rx["status"] != "active":
            raise HTTPException(status.HTTP_409_CONFLICT, "The prescription is no longer active")
        dispense_id = _new_fill(conn, rx, req["pharmacy_id"])
        conn.execute(
            """
            UPDATE medication_requests
            SET refills_authorized = refills_authorized + 1 + %s, refills_remaining = refills_remaining + %s
            WHERE id = %s
            """,
            (body.additional_refills, body.additional_refills, rx["id"]),
        )
    new_status = "approved" if body.decision == "approve" else "denied"
    conn.execute(
        """
        UPDATE refill_requests SET status = %s, decision_note = %s, decided_by = %s, decided_at = now(), dispense_id = %s
        WHERE id::text = %s
        """,
        (new_status, note, user.id, dispense_id, request_id),
    )
    if req["review_item_id"]:
        resolution = f"refill_{new_status}" + (f": {note}" if note else "")
        conn.execute(
            """
            UPDATE review_items SET status = 'resolved', resolution = %s, resolved_by = %s, resolved_at = now()
            WHERE id = %s AND status = 'open'
            """,
            (resolution, user.id, req["review_item_id"]),
        )
    audit.record(conn, action=f"refill_{new_status}", entity_type="refill_request", entity_id=request_id, actor=user,
                 patient_id=req["patient_id"],
                 detail={"medication_request_id": rx["id"], "dispense_id": dispense_id,
                         "additional_refills": body.additional_refills, "review_item_id": req["review_item_id"]})
    return {"id": request_id, "status": new_status, "dispense_id": dispense_id, "decision_note": note}


# --- Dose log --------------------------------------------------------------------------------


class DoseIn(BaseModel):
    model_config = ConfigDict(extra="forbid")
    taken_on: date | None = None


def _dose_target(conn: Connection, user: User, rx_id: str) -> dict:
    rx = _load_rx(conn, user, rx_id)
    if user.role != "patient":
        raise HTTPException(status.HTTP_403_FORBIDDEN, "Only the patient logs their doses")
    if rx["status"] != "active":
        raise HTTPException(status.HTTP_409_CONFLICT, "This prescription isn't active")
    return rx


@router.post("/prescriptions/{rx_id}/doses", status_code=status.HTTP_201_CREATED)
def log_dose(rx_id: str, body: DoseIn, conn: Conn, user: Patient) -> dict:
    rx = _dose_target(conn, user, rx_id)
    today = clinic_today()
    day = body.taken_on or today
    if day > today:
        raise HTTPException(status.HTTP_422_UNPROCESSABLE_CONTENT, "You can't log a dose for a future day")
    if day < today - timedelta(days=6):
        raise HTTPException(status.HTTP_422_UNPROCESSABLE_CONTENT, "You can log doses for the last 7 days only")
    start = _tracking_start(conn, rx_id, SeedContext().tz)
    if start is None or day < start:
        raise HTTPException(status.HTTP_409_CONFLICT,
                            "Log doses once you've picked up this medicine from the pharmacy")
    row = conn.execute(
        """
        INSERT INTO medication_adherence_logs (medication_request_id, patient_id, taken_on) VALUES (%s, %s, %s)
        ON CONFLICT (medication_request_id, taken_on) DO NOTHING RETURNING id::text
        """,
        (rx_id, rx["patient_id"], day),
    ).fetchone()
    if row:
        audit.record(conn, action="dose_logged", entity_type="medication_request", entity_id=rx_id, actor=user,
                     patient_id=rx["patient_id"], detail={"taken_on": day})
    return {"taken_on": day, "adherence": adherence_for(conn, rx_id)}


@router.delete("/prescriptions/{rx_id}/doses/{taken_on}")
def unlog_dose(rx_id: str, taken_on: date, conn: Conn, user: Patient) -> dict:
    rx = _dose_target(conn, user, rx_id)
    deleted = conn.execute(
        "DELETE FROM medication_adherence_logs WHERE medication_request_id = %s AND taken_on = %s RETURNING id",
        (rx_id, taken_on),
    ).fetchone()
    if deleted:
        audit.record(conn, action="dose_unlogged", entity_type="medication_request", entity_id=rx_id, actor=user,
                     patient_id=rx["patient_id"], detail={"taken_on": taken_on})
    return {"taken_on": taken_on, "adherence": adherence_for(conn, rx_id)}


# --- Drug information and interactions (curated tables only) ---------------------------------


def _monograph(conn: Connection, code: str) -> dict | None:
    row = conn.execute(
        """
        SELECT code, name, drug_class, uses, how_to_take, common_side_effects, call_doctor_if
        FROM drug_monographs WHERE code = %s
        """,
        (code,),
    ).fetchone()
    if row:
        row["notice"] = DRUG_INFO_NOTICE
        row["source"] = "Bioverse demo monograph (curated)"
    return row


@router.get("/drugs")
def list_drugs(conn: Conn, user: CurrentUser) -> dict:
    rows = conn.execute("SELECT code, name, drug_class FROM drug_monographs ORDER BY name").fetchall()
    return {"drugs": rows, "notice": DRUG_INFO_NOTICE}


@router.get("/drugs/{code}")
def get_drug(code: str, conn: Conn, user: CurrentUser) -> dict:
    row = _monograph(conn, code)
    if row is None:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "No demo information for that medicine")
    return row


def interactions_for(conn: Connection, patient_id: str, candidate: str | None = None) -> dict:
    """Curated pairs among the patient's active medicines (plus an optional candidate drug)."""
    active = conn.execute(
        "SELECT DISTINCT drug_code, drug_name FROM medication_requests WHERE patient_id = %s AND status = 'active'",
        (patient_id,),
    ).fetchall()
    names = {r["drug_code"]: r["drug_name"] for r in active}
    codes = set(names)
    if candidate:
        cand = conn.execute("SELECT code, name FROM drug_monographs WHERE code = %s", (candidate,)).fetchone()
        if cand is None:
            raise HTTPException(status.HTTP_404_NOT_FOUND, "That medicine isn't in the demo interaction list")
        names.setdefault(cand["code"], cand["name"])
    check = codes | ({candidate} if candidate else set())
    rows = conn.execute(
        """
        SELECT i.id::text, i.drug_a, i.drug_b, i.substance, i.severity, i.summary, i.advice,
               a.name AS drug_a_name, b.name AS drug_b_name
        FROM drug_interactions i
        JOIN drug_monographs a ON a.code = i.drug_a
        LEFT JOIN drug_monographs b ON b.code = i.drug_b
        WHERE (i.drug_b IS NOT NULL AND i.drug_a = ANY(%(c)s) AND i.drug_b = ANY(%(c)s))
           OR (i.drug_b IS NULL AND i.drug_a = ANY(%(c)s))
        """,
        {"c": list(check)},
    ).fetchall()
    warnings = []
    order = {"major": 0, "moderate": 1, "advisory": 2}
    for r in rows:
        pair = {r["drug_a"], r["drug_b"]} if r["drug_b"] else {r["drug_a"]}
        warnings.append({
            "id": r["id"],
            "kind": "drug" if r["drug_b"] else "food",
            "severity": r["severity"],
            "between": [r["drug_a_name"], r["drug_b_name"] or r["substance"]],
            "involves_candidate": bool(candidate and candidate in pair),
            "summary": r["summary"],
            "advice": r["advice"],
        })
    warnings.sort(key=lambda w: (order[w["severity"]], w["between"]))
    return {"checked": sorted(names[c] for c in check if c in names), "warnings": warnings,
            "notice": INTERACTION_NOTICE, "source": "Bioverse curated demo interaction list"}


@router.get("/interactions")
def check_interactions(conn: Conn, user: CurrentUser, patient_id: str | None = None, candidate: str | None = None) -> dict:
    pid = _patient_scope(conn, user, patient_id)
    out = interactions_for(conn, pid, candidate)
    audit.record(conn, action="interactions_checked", entity_type="medication_request", actor=user, patient_id=pid,
                 detail={"candidate": candidate, "warnings": len(out["warnings"])})
    return out
